name: Publish Gem

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Bundle install
      run: bundle

    - name: Build Gem
      run: rake build
    
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{secrets.RUBYGEMS_API_KEY}}

    # - name: mkdir gem
    #   run: mkdir ~/.gem

    # - name: Add api key
    #   run: "echo :rubygems_api_key: $RUBYGEMS_API_KEY > ~/.gem/credentials"
    #   env:
    #     RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

    # - name: test
    #   run: cat ~/.gem/credentials

    # - name: test2
    #   run: git status

    # - name: test3
    #   run: "echo $RUBYGEMS_API_KEY"
    #   env:
    #     RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

    # - name: set git username
    #   run: git config user.name "Aitaro Chaya"
      
    # - name: set git email
    #   run: git config user.email "aitaro.chaya@gmail.com"

    # - name: Release Gem
    #   run: rake release